name: Test

on:
pull_request:
  types:
    - synchronize
    - opened
    - reopened
    - unlocked
  paths:
    - "src/**"
push:
  branches:
    - main
  paths:
    - "src/**"
workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node 22
        uses: actions/setup-node@v5
        with:
          node-version: "22.18.0"

      - uses: extractions/setup-just@v3

      - name: Install dependencies
        run: just deps-extension

      - name: Run tests with coverage
        run: just test coverage
